version: 2.0.0.{build}

install:
  appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - cmd: git submodule -q update --init


before_build:
- cmd: nuget restore

build:
  verbosity: minimal
  
nuget:
  account_feed: true
  project_feed: true
